more ci debugging

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -63,7 +63,7 @@ orbs:
               git -C $PANTHEON_REPO_DIR fetch pantheon
 
 
-              REMOTE_REF=$(git -C $PANTHEON_REPO_DIR ls-remote pantheon | grep "refs/heads/$TERMINUS_ENV$")
+              REMOTE_REF=$(git -C $PANTHEON_REPO_DIR ls-remote pantheon | grep "refs/heads/$TERMINUS_ENV$") || echo "hmm, assigning an empty var returns an error."
 
               if [ -n "$REMOTE_REF" ]; then
                 git -C $PANTHEON_REPO_DIR checkout $TERMINUS_ENV
